[Feature/daengle] 사용자 프로필 수정 api 연동 및 S3 사진 업로드 기능 구현
DDog-org/daengle-client pull request #187
Opened 2024-12-07 18:07 UTC by Yunil-dev

## 🍡 연관된 이슈 번호

- close #68 

<br/>

## 📝 관련 문서 레퍼런스

- [Slack] :
- [Notion] :

<br/>

## 💻 주요 변경 사항은 무엇인가요?

- 프로필 사진 썸네일 기능 추가
- 프로필 수정 api 연동

<br/>

## 📚 추가된 라이브러리

- [추가] : NO

<br/>

## 📱 결과 화면 (선택)

![Dec-08-2024 03-01-41](https://github.com/user-attachments/assets/a7bd6176-9b62-47d4-a099-801a402ff2ca)

<br/>

## 🙇 코드 리뷰 중점사항, 예상되는 문제점 (선택)

- 폴더 구조는 story 브랜치에 모두 머지 후 수정하도록 하겠습니다 !

2024-12-08 06:11 UTC, corinthionia approved these changes
고생하셨어요~~

2024-12-08 06:37 UTC, MOONProd approved these changes
수고 많으셨습니다!!

2024-12-08 07:22 UTC, corinthionia requested changes

2024-12-09 10:11 UTC, corinthionia commented on packages/services/src/apis/config/index.ts
> +    const token = process.env.NEXT_PUBLIC_TOKEN;
이렇게 변경하면 안 되지 않나요?? 👀

2024-12-09 13:11 UTC, corinthionia approved these changes

2024-12-09 13:12 UTC, merged