[Story/groomer] 미용사는 견적서를 조회 할 수 있다.
DDog-org/daengle-client pull request #189
Opened 2024-12-08 07:17 UTC by MOONProd

## 🍡 연관된 이슈 번호

- close #10 

<br/>

## 📝 관련 문서 레퍼런스

- [Slack] : 
- [Notion] : https://www.notion.so/981021/2d77e81bf81f413690b30c8a1918138d?pvs=4#40fb97e515494364a1e20e761b1d3982

<br/>

## 💻 주요 변경 사항은 무엇인가요?

- groomer 폴더의 견적서 리스트 (estimate) 견적서 상세 조회 (estimate/detail/[id]) 페이지가 추가 되었습니다
- 공통으로 이용되는 컴포넌트는 `packages/services/src/components/estimate`에 위치시켰습니다

<br/>

## 📚 추가된 라이브러리

- [추가] : YES
- 달력을 위한 dayjs @emotion-styled @mui-x-date-pickers @mui-material

<br/>

## 📱 결과 화면 (선택)

<br/>

## 🙇 코드 리뷰 중점사항, 예상되는 문제점 (선택)

- 추후 수정사항이 생길 수 있습니다!

2024-12-08 07:23 UTC, Yunil-dev approved these changes
고생하셨습니다 !

2024-12-08 14:10 UTC, corinthionia requested changes

2024-12-09 06:50 UTC, corinthionia approved these changes
고생하셨습니다!!!

2024-12-09 09:00 UTC, corinthionia approved these changes

2024-12-09 09:01 UTC, merged