[Feature/daengle] 반려견 등록하기 페이지 api 연동
DDog-org/daengle-client pull request #231
Opened 2024-12-11 16:31 UTC by Yunil-dev

## 🍡 연관된 이슈 번호

- close #161 

<br/>

## 📝 관련 문서 레퍼런스

- [Slack] :
- [Notion] :

<br/>

## 💻 주요 변경 사항은 무엇인가요?

- 반려견 프로필 사진 등록 기능 구현
- 반려견 프로필 등록 api 연동

<br/>

## 📚 추가된 라이브러리

- [추가] : NO

<br/>

## 📱 결과 화면 (선택)

<br/>

## 🙇 코드 리뷰 중점사항, 예상되는 문제점 (선택)

- story 머지 후 폴더구조 리팩토링 하겠습니다 !

2024-12-11 16:35 UTC, corinthionia requested changes

2024-12-11 17:03 UTC, jejukyj approved these changes
고생하셨습니다^~^

2024-12-12 12:08 UTC, corinthionia requested changes

2024-12-12 12:25 UTC, corinthionia approved these changes

2024-12-12 12:25 UTC, merged