[Feature/package] 카카오 로그인 api 연동
DDog-org/daengle-client pull request #49
Opened 2024-11-23 17:11 UTC by kyoul10121

## 🍡 연관된 이슈 번호

- close #4 

<br/>

## 📝 관련 문서 레퍼런스

```
- [Slack] :
- [Notion] :
```

<br/>

## 💻 주요 변경 사항은 무엇인가요?

```
- 카카오 서버에서 인가코드 , 토큰을 받은 후 서버에게 넘겨주는 기능을 구현했습니다.
```

<br/>

## 📚 추가된 라이브러리

```
- [추가] : NO
```

<br/>

## 📱 결과 화면 (선택)

<br/>

## 🙇 코드 리뷰 중점사항, 예상되는 문제점 (선택)

```
- 로그인 토큰 관리는 다른 이슈에서 진행합니다.
```

2024-11-23 17:19 UTC, MOONProd submitted a review, later dismissed
고생하셨습니다아

2024-11-23 17:37 UTC, corinthionia requested changes

2024-11-23 17:37 UTC, corinthionia commented on apps/daengle/pages/auth/callback.tsx
> +}
여기는 `pages/auth`인데 `pages/login`에서 컴포넌트를 불러오는 게 조금 이상한 것 같아요! (분리된 별도의 페이지이니까요)
그래서 Redirection 컴포넌트를 한다면 `auth/components/redirection/index.tsx`에 작성하는 게 좋을 것 같습니다

또한 컴포넌트의 파일명은 모두 `index.tsx`로 작성한다고 생각하시면 될 것 같아요
그래서 이 컴포넌트도 `pages/auth/callback/index.tsx`가 되어야 할 것 같습니다!

2024-11-23 17:37 UTC, corinthionia commented on apps/daengle/pages/auth/callback.tsx
> +}
추가적으로는 `<Redirection>` 컴포넌트를 굳이 분리한 이유는 나중에 package로 빼기 위함일까요?

2024-11-23 17:37 UTC, corinthionia commented on apps/daengle/pages/auth/index.tsx
> +}
`auth/index.tsx`와 `auth/callback.tsx`의 차이는 무엇인가요?!

2024-11-23 17:37 UTC, corinthionia commented on apps/daengle/src/pages/login/index.tsx
> +
상수는 컴포넌트 코드 밖으로 빼 주세요!
```suggestion
const REST_API_KEY = process.env.NEXT_PUBLIC_REST_API_KEY;
const REDIRECT_URI = process.env.NEXT_PUBLIC_REDIRECT_URI;
const kakaoAuthUrl = `https://kauth.kakao.com/oauth/authorize?response_type=code&client_id=${REST_API_KEY}&redirect_uri=${REDIRECT_URI}&response_type=code`;

export default function Login() {}
```

2024-11-23 17:37 UTC, corinthionia commented on apps/daengle/src/pages/login/redirection.tsx
> +  console.log('Authorization Code:', code);
PR 올릴 때에는 console.log를 모두 지워 주세요!

2024-11-23 17:37 UTC, corinthionia commented on apps/daengle/src/pages/login/redirection.tsx
> +        const serverResponse = await axios.post('https://dev-api.daengle.com/api/oauth/kakao', {
api 주소는 env 파일로 관리해 주세요!

2024-11-23 17:37 UTC, corinthionia commented on apps/daengle/src/pages/login/redirection.tsx
> +        const serverResponse = await axios.post('https://dev-api.daengle.com/api/oauth/kakao', {
react-query를 나중에 적용하는 것보다는 그때그때 적용하는 게 좋을 것 같아요! (안 그러면 react query 적용에 대한 PR을 또 올려야 해서...?!) api 호출에 대한 부분도 `api/oauth/index.ts`에 따로 분리해 주세요!

2024-11-23 17:37 UTC, corinthionia commented on apps/daengle/src/pages/login/sucess.tsx
> +
파일 이름이 잘못 작성된 것 같아요!

2024-11-23 17:46 UTC, kyoul10121 commented on apps/daengle/pages/auth/callback.tsx
> +}
<Redirection> 컴포넌트는 **로그인 중** 과 **로그인 성공** 페이지를 구분하고 싶어서 따로 뻇습니다 !
테스트할 때 화면이 구분가는 게 직관적인 거 같아서요!

하지만 주현님께서 남겨주신 리뷰보니 구조를 엉망으로 해둔게 보이네요🥹
바로 수정하도록 하겠습니다.

2024-11-24 13:13 UTC, corinthionia submitted a review, later dismissed
나중에 react-query도 적용해 주세욥!

2024-11-24 18:42 UTC, corinthionia requested changes

2024-11-24 18:42 UTC, corinthionia commented on apps/daengle/src/api/oauth/index.tsx
> +  }
api 호출 코드에서는 try catch 문을 지워 주세용!

2024-11-26 00:40 UTC, corinthionia requested changes

2024-11-26 00:40 UTC, corinthionia commented on apps/daengle/src/api/oauth/index.tsx
> +  await api.post('/api/oauth/kakao', {
return 문으로 작성해 주세요!
```suggestion
  return await api.post('/api/oauth/kakao', {
```

2024-11-26 00:40 UTC, corinthionia commented on apps/daengle/src/queries/oauth/index.tsx
> +    mutationKey: QUERY_KEYS.FETCH_KAKAO_ACCESS_TOKEN,
여기도 이름 바꿔야 할 거 같아요

2024-11-26 00:58 UTC, corinthionia submitted a review, later dismissed

2024-11-26 01:03 UTC, corinthionia approved these changes

2024-11-26 01:03 UTC, merged